using System.Collections;
using System.Collections.Generic;
using Unity.Netcode;
using UnityEngine;

public class DealDamageOnContact : MonoBehaviour
{
    [SerializeField] private int damage = 5;
    private ulong ownerClientId;

    public void SetOwner(ulong clientId)
    {
        this.ownerClientId = clientId;
    }
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.attachedRigidbody == null)
        {
            return;
        }
        if (collision.attachedRigidbody.TryGetComponent<NetworkObject>(out NetworkObject networkObject))
        {
            if(ownerClientId == networkObject.OwnerClientId)
            {
                return ;
            }
        }
        if (collision.attachedRigidbody.TryGetComponent<Health>(out Health health))
        {
            health.TakeDamage(damage);
        }
    }
}
